name: release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: 下载源码
      uses: actions/checkout@v3
    - name: 初始化
      run: |
        sudo apt-get -y install gcc-11 gcc-11-multilib nasm p7zip-full autoconf automake make patch binutils-dev liblzma-dev gcc-mingw-w64-i686
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11
        sudo apt-get update
        sudo apt-get install --fix-missing
    - name: 编译
      run: |
        make -C umbr
        make -j -C g4dext
        make -j -C g4eext
        make -C grubutils/fbinst OSTYPE=MINGW CC=i686-w64-mingw32-gcc
        make -C grubutils/loadbin
        make -C grubutils/makemod OSTYPE=MINGW CC=i686-w64-mingw32-gcc
        make -C grubutils/makerom OSTYPE=MINGW CC=i686-w64-mingw32-gcc
        make -C grubutils/wee
        make -C grubutils/weesetup OSTYPE=MINGW CC=i686-w64-mingw32-gcc
        7z a grubutils.7z grubutils/fbinst/fbinst.exe grubutils/loadbin/*.bin grubutils/makemod/makemod.exe grubutils/makerom/makerom.exe grubutils/makerom/*.bin grubutils/weesetup/weesetup.exe

    - name: 上传
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Development Build"
        files: |
            g4dext-*.zip
            g4eext-*.zip
            grubutils.7z
